version: "3.4"

services:
  php:
    build:
      context: .
      target: app_php

    volumes:
      - php_socket:/var/run/php
   
    ports:
      # HTTP
      - 8080:80
      - 8000:8000
      # HTTPS
      - 443:443

volumes:
  php_socket:
